// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int64              `json:"id"`
	ShortCode   string             `json:"short_code"`
	Destination string             `json:"destination"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
