// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    short_code,
    destination
) VALUES ($1, $2) RETURNING id, short_code, destination, created_at
`

type CreateURLParams struct {
	ShortCode   string `json:"short_code"`
	Destination string `json:"destination"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.Destination)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}
